version: '3.8d'

# hard coded for purposes of this assignment
# in production ports, user, password, and db would be stored in .env file
services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql